# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Title', models.CharField(max_length=100)),
                ('Start_Date', models.CharField(help_text=b'Enter as MM/DD/YYYY', max_length=10)),
                ('End_Date', models.CharField(help_text=b'Enter as MM/DD/YYYY', max_length=10)),
                ('Hashtag', models.CharField(help_text=b"Don't type the '#'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('img_url', models.TextField()),
                ('img_owner', models.CharField(max_length=50)),
                ('post_link', models.TextField(default=b'http://www.google.com', max_length=300)),
                ('pub_date', models.IntegerField()),
            ],
        ),
    ]
