# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ig_miner_app', '0002_photo_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='campaign_id',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='ig_miner_app.Campaign'),
        ),
    ]
