# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_miner_app', '0004_auto_20160502_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='campaign_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='campaign_title',
            field=models.CharField(default=b'default campaign', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='Campaign_Title',
            field=models.CharField(help_text=b'Must be different than your other campaigns!', max_length=100, unique=True),
        ),
    ]
