# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_miner_app', '0005_auto_20160502_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='campaign_title',
            field=models.CharField(default=b'default campaign', max_length=100),
        ),
    ]
