# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_miner_app', '0008_auto_20160506_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='Campaign_Title',
            field=models.CharField(max_length=100),
        ),
    ]
